-- Database: history_peserta_wisuda
-- Table: peserta_wisuda

CREATE TABLE IF NOT EXISTS peserta_wisuda (
    npm VARCHAR(32) NOT NULL,
    periode INTEGER NOT NULL,
    fakultas VARCHAR(120),
    prodi VARCHAR(120),
    program VARCHAR(120),
    status_awal VARCHAR(120),
    mhs_angkatan VARCHAR(10),
    peserta_valid BOOLEAN,
    nama VARCHAR(200),
    jenis_kelamin VARCHAR(20),
    ukuran_toga VARCHAR(20),
    catatan TEXT,
    email VARCHAR(200),
    telepon1 VARCHAR(50),
    telepon2 VARCHAR(50),
    tempat_lahir VARCHAR(120),
    tanggal_lahir DATE,
    tanggal_lulus DATE,
    masa_studi_bulan INTEGER,
    masa_studi_tahun NUMERIC(4,2),
    nama_ayah VARCHAR(200),
    pekerjaan_ortu VARCHAR(200),
    jabatan_ortu VARCHAR(200),
    ipk NUMERIC(3,2),
    sks INTEGER,
    predikat VARCHAR(120),
    judul_ta_skripsi TEXT,
    catatan_upt TEXT,
    catatan_rc TEXT,
    catatan_dpk TEXT,
    catatan_bpc TEXT,
    catatan_daak TEXT,
    approve_upt BOOLEAN,
    approve_rc BOOLEAN,
    approve_dpk BOOLEAN,
    approve_bpc BOOLEAN,
    approve_daak BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (npm, periode)
);

CREATE INDEX IF NOT EXISTS idx_peserta_wisuda_periode
    ON peserta_wisuda (periode);

CREATE TABLE IF NOT EXISTS peserta_wisuda_raw (
    npm VARCHAR(32) NOT NULL,
    periode INTEGER NOT NULL,
    fakultas TEXT,
    prodi TEXT,
    program TEXT,
    status_awal TEXT,
    mhs_angkatan TEXT,
    peserta_valid TEXT,
    nama TEXT,
    jenis_kelamin TEXT,
    ukuran_toga TEXT,
    catatan TEXT,
    email TEXT,
    telepon1 TEXT,
    telepon2 TEXT,
    tempat_lahir TEXT,
    tanggal_lahir TEXT,
    tanggal_lulus TEXT,
    masa_studi_bulan TEXT,
    masa_studi_tahun TEXT,
    nama_ayah TEXT,
    pekerjaan_ortu TEXT,
    jabatan_ortu TEXT,
    ipk TEXT,
    sks TEXT,
    predikat TEXT,
    judul_ta_skripsi TEXT,
    catatan_upt TEXT,
    catatan_rc TEXT,
    catatan_dpk TEXT,
    catatan_bpc TEXT,
    catatan_daak TEXT,
    approve_upt TEXT,
    approve_rc TEXT,
    approve_dpk TEXT,
    approve_bpc TEXT,
    approve_daak TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (npm, periode)
);

CREATE INDEX IF NOT EXISTS idx_peserta_wisuda_raw_periode
    ON peserta_wisuda_raw (periode);
